### ISSUE TITLE
Distinctives of this implementation?

### ISSUE THREAD

**Issue by Stratus3D** [fogfish/crdts#1]
Looking online for CRDT implementations I came across this repository and https://github.com/basho/riak_dt. Are both projects different implementations of the same CRDT algorithm? Are there any significant differences between the two?

Thanks!

**Comment by fogfish** [comment]
Thank you for raising the question!

This library has focused a few purposes in the contrast to existing one:
1. propose a common interface to deal with CRDTs structs, so that `crdts:new(...)`, `crdts:update(...)` and `crdts:value(...)`, please see crdts.erl. There is a believe that common interface helps with adoption of various CRDTs sets to the app. 
2. the library explicitly defines the notion of the time using k-ordered value (https://github.com/fogfish/uid), while other libs does says that this is a client problem. The "time" is a curtail concept in CRDTs thus I've been upset with the fact that other libs does not resolve it.

Otherwise, I would not see bid diff. Of course, I've never advertised this library in the community thus it is "less" used to compare with basho one.

**Comment by Stratus3D** [comment]
Thanks for the response! 

> There is a believe that common interface helps with adoption of various CRDTs sets to the app.

Yes, I agree. I'm currently exploring CRDT implementations for a collaborative software project (e.g. google docs but for a markup language). I'm trying to figure out what format would be best to store the text in - AST or a plain string. This is a hobby project.

I've come across https://github.com/yjs/yjs for the frontend which appears suited to my needs on the frontend, so I'm looking to possibly to implement it in Erlang or modify an existing Erlang CRDT library to support it. Any suggestions are welcome! I'm new to CRDTs and collaborative applications.
